apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- ingress.yaml
configMapGenerator:
- name: es-config
  files:
    - config/jvm.options
    - config/elasticsearch.yml
    - config/log4j2.properties